source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'

target 'ExampleIOS' do
  use_frameworks!
  pod 'TestFlutterSDK', :podspec => '../../TestFlutterSDK.podspec'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['LD_RUNPATH_SEARCH_PATHS'] ||= ['$(inherited)']
      end
    end
  end
end
